# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cart_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='test',
        ),
    ]
