# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20151209_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='000888AA', max_length=10),
            preserve_default=False,
        ),
    ]
