# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20151208_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbillingaddress',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='usermailingaddress',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userbillingaddress',
            name='last_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermailingaddress',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
